// TODO: replace static options with live F1 Fantasy feed.
export const DRIVER_OPTIONS = [
  "Max Verstappen",
  "Isack Hadjar",
  "Lando Norris",
  "Oscar Piastri",
  "Charles Leclerc",
  "Lewis Hamilton",
  "George Russell",
  "Kimi Antonelli",
  "Fernando Alonso",
  "Lance Stroll",
  "Carlos Sainz",
  "Alex Albon",
  "Liam Lawson",
  "Arvid Lindblad",
  "Esteban Ocon",
  "Oliver Bearman",
  "Pierre Gasly",
  "Franco Colapinto",
  "Nico Hulkenberg",
  "Gabriel Bortoleto",
  "Sergio Perez",
  "Valtteri Bottas",
];

export const CONSTRUCTOR_OPTIONS = [
  "Red Bull Racing",
  "McLaren",
  "Ferrari",
  "Mercedes",
  "Aston Martin",
  "Williams",
  "Racing Bulls",
  "Haas",
  "Alpine",
  "Audi",
  "Cadillac",
];

export const DRIVER_PRICES: Record<string, number> = {
  "Max Verstappen": 30.0,
  "Lando Norris": 29.0,
  "Oscar Piastri": 28.0,
  "Charles Leclerc": 25.0,
  "Lewis Hamilton": 23.0,
  "George Russell": 24.0,
  "Kimi Antonelli": 21.0,
  "Isack Hadjar": 18.0,
  "Fernando Alonso": 13.0,
  "Lance Stroll": 8.0,
  "Carlos Sainz": 17.0,
  "Alex Albon": 10.0,
  "Liam Lawson": 8.0,
  "Arvid Lindblad": 6.0,
  "Esteban Ocon": 9.0,
  "Oliver Bearman": 7.0,
  "Pierre Gasly": 8.0,
  "Franco Colapinto": 6.0,
  "Nico Hulkenberg": 7.0,
  "Gabriel Bortoleto": 5.0,
  "Sergio Perez": 12.0,
  "Valtteri Bottas": 7.0,
};

export const CONSTRUCTOR_PRICES: Record<string, number> = {
  "Red Bull Racing": 27.0,
  McLaren: 24.0,
  Ferrari: 23.0,
  Mercedes: 20.0,
  "Aston Martin": 14.0,
  Williams: 9.0,
  "Racing Bulls": 8.0,
  Haas: 7.0,
  Alpine: 7.0,
  Audi: 6.0,
  Cadillac: 6.0,
};
